from __future__ import annotations

DEFAULT_CONFIG = {
    "executor_type": "protocol",
    "mail_provider": "luckmail",
    "count": 1,
    "concurrency": 1,
    "register_delay_seconds": 0,
    "use_proxy": True,
    "proxy": "",
    "luckmail_base_url": "https://mails.luckyous.com/",
    "luckmail_api_key": "",
    "luckmail_email_type": "",
    "luckmail_domain": "",
    "tempmail_api_base": "https://api.tempmail.lol/v2",
    "cpa_api_url": "",
    "cpa_api_key": "",
    "sub2api_api_url": "",
    "sub2api_api_key": "",
    "sub2api_group_ids": "2",
    "codexproxy_api_url": "",
    "codexproxy_admin_key": "",
    "codexproxy_proxy_url": "",
    "auto_upload_target": "both",
    "inbound_upload_auth_token": "",
    "smstome_cookie": "",
    "smstome_country_slugs": "united-kingdom,poland,finland",
    "smstome_phone_attempts": 3,
    "smstome_otp_timeout_seconds": 45,
    "smstome_poll_interval_seconds": 5,
    "smstome_sync_max_pages_per_country": 5,
    "chatgpt_register_otp_wait_seconds": 600,
    "chatgpt_register_otp_resend_wait_seconds": 300,
}
